/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hundirLaFlota;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Javie
 */
public class panelListaBarcos extends javax.swing.JPanel {

    /**
     * Creates new form panelListaBarcos
     */
    public panelListaBarcos(int numeroDeCuadrados) {
        initComponents();
        GridLayout gridLayout = new GridLayout(1, 5);
        jpn_dibujo.setLayout(gridLayout);
        for (int i = 0; i < 5; i++) {
            JPanel panel = new JPanel();
            if (numeroDeCuadrados > 0) {
                panel.setBackground(Color.lightGray);
                panel.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            }
            jpn_dibujo.add(panel);
            numeroDeCuadrados = numeroDeCuadrados -1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_dibujo = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 2));

        jpn_dibujo.setName("dibujo"); // NOI18N

        javax.swing.GroupLayout jpn_dibujoLayout = new javax.swing.GroupLayout(jpn_dibujo);
        jpn_dibujo.setLayout(jpn_dibujoLayout);
        jpn_dibujoLayout.setHorizontalGroup(
            jpn_dibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        jpn_dibujoLayout.setVerticalGroup(
            jpn_dibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        add(jpn_dibujo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpn_dibujo;
    // End of variables declaration//GEN-END:variables
}
